---
- name: Enable Developer Mode
  ansible.windows.win_regedit:
    path: HKLM:\Software\Microsoft\Windows\CurrentVersion\AppModelUnlock
    name: AllowDevelopmentWithoutDevLicense
    data: 1
    type: dword

- name: Show hidden files
  ansible.windows.win_regedit:
    path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced
    name: Hidden
    data: 1
    type: dword

- name: Show protected OS files
  ansible.windows.win_regedit:
    path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced
    name: ShowSuperHidden
    data: 1
    type: dword

- name: Nav pane expands to current folder
  ansible.windows.win_regedit:
    path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced
    name: NavPaneExpandToCurrentFolder
    data: 1
    type: dword

- name: Show all folders in nav pane
  ansible.windows.win_regedit:
    path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced
    name: NavPaneShowAllFolders
    data: 1
    type: dword

- name: This PC is default explorer view
  ansible.windows.win_regedit:
    path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced
    name: LaunchTo
    data: 1
    type: dword

- name: Show file extensions
  ansible.windows.win_regedit:
    path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced
    name: HideFileExt
    data: 0
    type: dword

- name: Taskbar where window is open for multi-monitor
  ansible.windows.win_regedit:
    path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced
    name: MMTaskbarMode
    data: 2
    type: dword

- name: Refresh registry to make changes take effect
  ansible.windows.win_shell: RUNDLL32.EXE user32.dll,UpdatePerUserSystemParameters

- name: Remove default apps
  ansible.windows.win_package:
    product_id: "{{ item }}"
    state: absent
  with_items: "{{ default_apps }}"

- name: Install common dev tools
  chocolatey.chocolatey.win_chocolatey:
    name: "{{ item }}"
    state: present
  with_items: "{{ dev_tools }}"

- name: Install Git
  chocolatey.chocolatey.win_chocolatey:
    name: git
    package_params: "'/GitAndUnixToolsOnPath /WindowsTerminal'"
    state: present

- name: Install VS with Git
  chocolatey.chocolatey.win_chocolatey:
    name: visualstudio2019community
    package_params: "'--add Microsoft.VisualStudio.Component.Git'"
    state: present

- name: refreshenv
  ansible.windows.win_shell: refreshenv

- name: Install VS workloads
  chocolatey.chocolatey.win_chocolatey:
    name: "{{ item }}"
    state: present
  with_items:
    - visualstudio2019-workload-azure
    - visualstudio2019-workload-manageddesktop
